baseURL = "https://rougerose.github.io/pourmagnelli/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Pour Magnelli"
theme = "pourmagnelli-theme"
pluralizeListTitles = false
canonifyURLs = true
# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "association"
    title = "L'association"
    url = "/association/"
    weight = 1
  [[menu.main]]
    identifier = "magnelli"
    title = "Magnelli"
    url = "/magnelli/"
    weight = 2
  [[menu.main]]
    identifier = "actualites"
    title = "Actualités"
    url = "/actualites/"
    weight = 3

[params]
  jsLib = true
  mobileMenu = true
